services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: tabtempo
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: tabtempo_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: