version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: tabtempo
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: tabtempo_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tabtempo-net

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tabtempo.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - tabtempo-net

  api:
    build:
      context: ../api/tabtempo-api
      dockerfile: Dockerfile
    image: tabtempo-api:latest
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=tabtempo_dev;Username=tabtempo;Password=devpass"
      JwtSettings__Key: "ThisIsASuperSecretKey123!"
      JwtSettings__Issuer: "TabTempoAPI"
      JwtSettings__Audience: "TabTempoClient"
      JwtSettings__ExpiresInMinutes: "60"
    depends_on:
      - db
    networks:
      - tabtempo-net

  viewer:
    build:
      context: ../viewer
      dockerfile: Dockerfile
    image: tabtempo-viewer:latest
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - tabtempo-net

volumes:
  postgres_data:

networks:
  tabtempo-net: